apiVersion: projctl.konflux.dev/v1beta1
kind: ProjectDevelopmentStreamTemplate
metadata:
  name: fbc-project-template
spec:
  project: fbc
  variables:
  - name: fbcVersion
    description: FBC version number e.g fbc-v4-18-1-1
  - name: gitRevision
    description: The git revision we want to onbaord
  - name: gitContext
    description: The git context we want to use

  resources:
  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Application
    metadata:
      annotations:
        application.thumbnail: "9"
      name: "{{.fbcVersion}}"
    spec:
      displayName: "{{.fbcVersion}}"

  - apiVersion: appstudio.redhat.com/v1alpha1
    kind: Component
    metadata:
      annotations:
        build.appstudio.openshift.io/pipeline: '{"name":"fbc-builder","bundle":"latest"}'
        build.appstudio.openshift.io/status: '{"pac":{"state":"enabled","merge-url":"https://github.com/securesign/fbc/pull/97","configuration-time":"Thu,27 Mar 2025 12:35:34 UTC"},"message":"done"}'
      name: "{{.fbcVersion}}"
    spec:
      application: "{{.fbcVersion}}"
      componentName: "{{.fbcVersion}}"
      source:
        git:
          context: "{{ .gitContext }}"
          dockerfileUrl: catalog.Dockerfile
          revision: "{{.gitRevision}}"
          url: https://github.com/securesign/fbc

