apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "release-1.2" && 
      ( "v4.17/***".pathChanged() || ".tekton/fbc-v4-17-push.yaml".pathChanged() || "trigger-konflux-builds.txt".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fbc-v4-17-v1-2
    appstudio.openshift.io/component: fbc-v4-17-v1-2
    pipelines.appstudio.openshift.io/type: build
  name: fbc-v4-17-v1-2-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/fbc-v4-17-v1-2:{{revision}}
  - name: dockerfile
    value: catalog.Dockerfile
  - name: path-context
    value: v4.17
  pipelineRef:
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-fbc-v4-17-v1-2
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
