apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "main" && ( "v4.14/***".pathChanged() || ".tekton/fbc-v4-14-push.yaml".pathChanged()
      || "trigger-konflux-builds.txt".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fbc-v4-14
    appstudio.openshift.io/component: fbc-v4-14
    pipelines.appstudio.openshift.io/type: build
  name: fbc-v4-14-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: dockerfile
    value: catalog.Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: output-image
    value: quay.io/securesign/fbc-v4-14:{{revision}}
  - name: path-context
    value: v4.14
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/fbc-builder.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-fbc-v4-14
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
