apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/securesign/fbc?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && ( "v4.14/model-validation-operator/***".pathChanged() || ".tekton/mvo-fbc-v4-14-pull-request.yaml".pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: mvo-fbc-v4-14
    appstudio.openshift.io/component: mvo-fbc-v4-14
    pipelines.appstudio.openshift.io/type: build
  name: mvo-fbc-v4-14-on-pull-request
  namespace: rhtas-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/mvo-fbc-v4-14:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: build-platforms
    value:
    - linux/x86_64
  - name: dockerfile
    value: catalog.Dockerfile
  - name: path-context
    value: v4.14/model-validation-operator
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/fbc-builder.yaml
    resolver: git
  taskRunSpecs:
  - pipelineTaskName: fbc-fips-check-oci-ta
    stepSpecs:
    - computeResources:
        limits:
          memory: 3Gi
      name: fbc-fips-check-oci-ta
  - pipelineTaskName: fbc-target-index-pruning-check
    stepSpecs:
    - computeResources:
        limits:
          memory: 3Gi
      name: fbc-target-index-pruning-check
  taskRunTemplate:
    serviceAccountName: build-pipeline-mvo-fbc-v4-14
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
